package challenge.dao.mapper;

import challenge.model.Person;
import org.springframework.jdbc.core.RowMapper;

import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * This class is reponsible to map
 * person details with a dto
 * @Author Mayank Gupta
 * @Date 8/16/17
 */
public class PersonRowMapper implements RowMapper {


    /**
     * This method is responsible to return a person
     * based on the output result set generated by
     * the output query
     *
     * @param resultSet
     * @param i
     * @return Person
     * @throws SQLException
     */
    @Override
    public Person mapRow(ResultSet resultSet, int i) throws SQLException {

        Person person = new Person();
        person.setPersonId(resultSet.getInt(1));
        person.setHandle(resultSet.getString(2));
        person.setName(resultSet.getString(3));
        return person;
    }
}
